# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18113e4ce561e3b5a76b8a8797bcbdf6bda0bd22980c2b1bef86c8c1ee6186a5229f8735361cb8c8707d6b332ee774a54b6a4d5f489fd234c43690e52ba9f282

test:
  secret_key_base: 3a968e11ff9a432e105a6e37c896b6504e333f4e758e7811c1908727b36469308fa139d9449707b113410ca6526a2c51ccec8c3c46cd504ad6d3ddbc080799ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
